# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
- group: infravars

stages:
- stage: CreateAppServicePlan
  displayName: Create App Service Plan stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(so)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az appservice plan create -g $(rg) -n $(asp) --is-linux --number-of-workers 1 --sku B1
          az webapp create -g $(rg) -p $(asp) -n $(wa) --runtime "node|10.14"
